package org.objectstyle.wolips.devserver;

import java.io.File;
import java.util.List;
import java.util.Map;

import org.eclipse.core.resources.IProject;
import org.objectstyle.wolips.variables.ParsleyProject;
import org.objectstyle.wolips.wizards.MavenProjectImporter;

/**
 * {@code /importProject?path=DIR} — brings an existing Maven project on disk into the workspace
 * through m2e (File → Import → Existing Maven Projects, without the clicking). The other half of
 * {@code /createProject}: for a project an agent generated by other means, cloned, or that simply
 * was never imported.
 *
 * <p>When the project declares a {@code principalClass} in {@code build.properties} (i.e. it is
 * an application) and has no launch configuration running that class yet, one is created, so the
 * imported app is immediately launchable through {@code /launch}.
 */
class ImportProjectHandler implements DevServerHandler {

	@Override
	public String handle(Map<String, String> params) throws Exception {
		final String pathParam = params.get("path");
		if (pathParam == null || pathParam.isBlank()) {
			return "{\"imported\":false,\"reason\":\"missing required parameter 'path' (the project directory, containing pom.xml)\"}";
		}
		final File dir = new File(CreateProjectHandler.expandHome(pathParam.trim())).getCanonicalFile();
		if (!new File(dir, "pom.xml").isFile()) {
			return "{\"imported\":false,\"reason\":\"no pom.xml in " + DevServerJson.escape(dir.toString()) + " - only Maven projects can be imported\"}";
		}

		final IProject already = CreateProjectHandler.projectAt(dir);
		if (already != null) {
			return "{\"imported\":false,\"reason\":\"already in the workspace as \\\"" + DevServerJson.escape(already.getName()) + "\\\" ("
					+ (already.isOpen() ? "open" : "closed - use /openProject?project=" + DevServerJson.escape(already.getName())) + ")\",\"project\":\""
					+ DevServerJson.escape(already.getName()) + "\"}";
		}

		final IProject project = MavenProjectImporter.importProject(dir);
		if (project == null) {
			return "{\"imported\":false,\"reason\":\"m2e found no importable Maven project in " + DevServerJson.escape(dir.toString()) + "\"}";
		}
		CreateProjectHandler.settle();

		final StringBuilder b = new StringBuilder();
		b.append("{\"imported\":true,\"project\":\"").append(DevServerJson.escape(project.getName()))
				.append("\",\"path\":\"").append(DevServerJson.escape(dir.toString())).append('"');

		final List<WorkspaceProblems.Problem> errors = WorkspaceProblems.javaErrors(project, 10);
		b.append(",\"compileErrors\":").append(errors.size());
		if (!errors.isEmpty()) {
			b.append(",\"problems\":").append(WorkspaceProblems.toJsonArray(errors));
		}

		// An application (build.properties names its principalClass) gets a launch config.
		final ParsleyProject parsleyProject = (ParsleyProject) project.getAdapter(ParsleyProject.class);
		final String mainClass = parsleyProject != null && parsleyProject.getBuildProperties() != null
				? parsleyProject.getBuildProperties().getPrincipalClass()
				: null;
		if (mainClass != null) {
			final String launchConfig = LaunchConfigCreator.ensure(project.getName(), mainClass);
			b.append(",\"mainClass\":\"").append(DevServerJson.escape(mainClass))
					.append("\",\"launchConfig\":\"").append(DevServerJson.escape(launchConfig))
					.append("\",\"hint\":\"start it with /launch?config=").append(DevServerJson.escape(launchConfig)).append("&waitForPort=1200\"");
		}
		return b.append('}').toString();
	}
}
