<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.objectstyle.woproject</groupId>
	<artifactId>wolips-project</artifactId>
	<version>5.7.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<url>https://github.com/undur/wolips/</url>

	<properties>
		<maven.compiler.release>21</maven.compiler.release>
		<maven.install.skip>true</maven.install.skip>
		<maven.deploy.skip>true</maven.deploy.skip>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<tycho.version>5.0.4</tycho.version>
		<env.ui.test>-Xms512m -Xmx2048m</env.ui.test>
	</properties>

	<issueManagement>
		<system>github</system>
		<url>https://github.com/undur/wolips/issues</url>
	</issueManagement>

	<inceptionYear>2024</inceptionYear>

	<organization>
		<name>ng-objects</name>
		<url>https://github.com/undur/</url>
	</organization>

	<repositories>
		<repository>
			<id>eclipse</id>
			<url>https://download.eclipse.org/releases/latest</url>
			<layout>p2</layout>
		</repository>
	</repositories>

	<distributionManagement>
		<repository>
			<id>github</id>
			<name>GitHub Packages</name>
			<url>https://maven.pkg.github.com/${github.repository}</url>
		</repository>
	</distributionManagement>

	<scm>
		<connection>scm:git:https://github.com/${github.repository}.git</connection>
		<developerConnection>scm:git:https://github.com/${github.repository}.git</developerConnection>
		<url>https://github.com/${github.repository}</url>
	</scm>

	<modules>
		<module>wolips.p2</module>
		<module>wolips.targetplatform</module>
		<module>wolips/plugins/parslips.tooling</module>
		<module>wolips/plugins/parslips.lsp</module>
		<module>wolips/plugins/ng.componenteditor</module>
		<module>wolips/features/ng.componenteditor.feature</module>
	</modules>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.3.0</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-compiler-plugin</artifactId>
					<version>${tycho.version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-maven-plugin</artifactId>
					<version>${tycho.version}</version>
					<extensions>true</extensions>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-p2-repository-plugin</artifactId>
					<version>${tycho.version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-source-plugin</artifactId>
					<version>${tycho.version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-p2-plugin</artifactId>
					<version>${tycho.version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-versions-plugin</artifactId>
					<version>${tycho.version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-surefire-plugin</artifactId>
					<version>${tycho.version}</version>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>target-platform-configuration</artifactId>
					<version>${tycho.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-compiler-plugin</artifactId>
				<configuration>
					<source>21</source>
					<target>21</target>
					<optimize>true</optimize>
					<showWarnings>true</showWarnings>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-repository-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-source-plugin</artifactId>
				<executions>
					<execution>
						<id>plugin-source</id>
						<goals>
							<goal>plugin-source</goal>
						</goals>
					</execution>
					<execution>
						<id>feature-source</id>
						<phase>package</phase>
						<goals>
							<goal>feature-source</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-p2-metadata</id>
						<phase>package</phase>
						<goals>
							<goal>p2-metadata</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-versions-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-surefire-plugin</artifactId>
				<configuration>
					<failIfNoTests>false</failIfNoTests>
					<useUIHarness>true</useUIHarness>
					<useUIThread>true</useUIThread>
					<!--<showEclipseLog>true</showEclipseLog> -->
					<!--<testFailureIgnore>true</testFailureIgnore> -->
					<argLine>${ui.test.vmargs}</argLine>
					<jvmArgs>
						<args>${ui.test.vmargs}</args>
					</jvmArgs>
					<bundleStartLevel>
						<bundle>
							<id>org.eclipse.equinox.launcher</id>
							<level>4</level>
							<autoStart>true</autoStart>
						</bundle>
					</bundleStartLevel>
					<dependencies>
						<!--						<dependency>-->
						<!--							<type>p2-installable-unit</type>-->
						<!--							<artifactId>org.eclipse.equinox.ds</artifactId>-->
						<!--						</dependency>-->
						<dependency>
							<type>p2-installable-unit</type>
							<artifactId>org.eclipse.equinox.event</artifactId>
						</dependency>
					</dependencies>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<configuration>
					<environments>
						<environment>
							<os>linux</os>
							<ws>gtk</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>linux</os>
							<ws>gtk</ws>
							<arch>aarch64</arch>
						</environment>
						<environment>
							<os>linux</os>
							<ws>gtk</ws>
							<arch>riscv64</arch>
						</environment>
						<environment>
							<os>win32</os>
							<ws>win32</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>win32</os>
							<ws>win32</ws>
							<arch>aarch64</arch>
						</environment>
						<environment>
							<os>macosx</os>
							<ws>cocoa</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>macosx</os>
							<ws>cocoa</ws>
							<arch>aarch64</arch>
						</environment>
					</environments>
					<target>
						<artifact>
							<groupId>org.objectstyle.woproject</groupId>
							<artifactId>wolips.targetplatform</artifactId>
							<version>5.7.0-SNAPSHOT</version>
						</artifact>
					</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
