package org.objectstyle.wolips.bindings.api;

import java.util.List;

import org.objectstyle.wolips.bindings.api.ApiextModel.Alternative;
import org.objectstyle.wolips.bindings.api.ApiextModel.Choose;
import org.objectstyle.wolips.bindings.api.ApiextModel.Constraint;
import org.objectstyle.wolips.bindings.api.ApiextModel.Obligation;
import org.objectstyle.wolips.bindings.api.ApiextModel.Requires;

/**
 * Generates a human-readable message for a typed {@link Constraint}, so an author need not write one
 * (apiext-format spec, § Constraints: "messages are generated by the consumer from the typed rule").
 * A {@code <choose min="1" max="1">} over {@code a, b, c} becomes
 * <em>"exactly one of a, b or c must be bound"</em>. An author {@code message} override, when present,
 * is preferred by the renderer and this class is not consulted.
 * <p>
 * English only for now — the whole point of generating from the typed rule (rather than the legacy
 * hand-written message) is that a localized consumer can swap this out without touching the files.
 */
public final class ApiextConstraintMessages {

	private ApiextConstraintMessages() {
		// static only
	}

	/** Returns a generated one-sentence description of the constraint (capitalized, period). Never null. */
	public static String describe(Constraint c) {
		final String s;
		if (c instanceof Choose) {
			s = describeChoose((Choose) c);
		}
		else if (c instanceof Requires) {
			s = describeRequires((Requires) c);
		}
		else {
			return "";
		}
		return sentence(s);
	}

	/** Capitalizes the first letter and ensures a trailing period. */
	private static String sentence(String s) {
		if (s == null || s.isEmpty()) {
			return "";
		}
		final String capped = Character.toUpperCase(s.charAt(0)) + s.substring(1);
		return capped.endsWith(".") ? capped : capped + ".";
	}

	private static String describeChoose(Choose choose) {
		final int n = choose.getAlternatives().size();
		final Integer min = choose.getMin();
		final Integer max = choose.getMax();
		final int lo = min != null ? min : 0;
		final Integer hi = max; // null = unbounded
		final String set = alternativeList(choose.getAlternatives());

		// Name the common cardinalities the way the spec does, falling back to a general phrasing.
		if (hi != null && hi == 1 && lo == 1) {
			return "exactly one of " + set + " must be bound";
		}
		if (hi != null && hi == 1 && lo == 0) {
			return "at most one of " + set + " may be bound";
		}
		if (lo == 1 && hi == null) {
			return "at least one of " + set + " must be bound";
		}
		if (lo >= 2 && hi == null) {
			return "at least " + lo + " of " + set + " must be bound";
		}
		if (hi != null && lo == 0) {
			return "at most " + hi + " of " + set + " may be bound";
		}
		if (hi != null && lo == hi) {
			return "exactly " + lo + " of " + set + " must be bound";
		}
		if (hi != null) {
			return "between " + lo + " and " + hi + " of " + set + " must be bound";
		}
		// hi == null, lo == 0 — vacuous; the validator flags this, but describe something sane.
		return "any number of " + set + " may be bound";
	}

	private static String describeRequires(Requires requires) {
		// Phrasing follows the wonder-slim reference: "<consequent> must be <obligation> [when <antecedent>]".
		final String consequent = quote(requires.getBinding());
		final String obligation = obligationPhrase(requires.getMust(), consequent);
		final Alternative antecedent = requires.getAntecedent();
		if (antecedent == null) {
			return obligation + "."; // unconditional (settable/gettable only)
		}
		return obligation + " when " + antecedentPhrase(antecedent) + ".";
	}

	private static String obligationPhrase(Obligation must, String consequent) {
		switch (must) {
		case SETTABLE:
			return consequent + " must be settable (assignable, not a constant)";
		case GETTABLE:
			return consequent + " must be a keypath, not a constant";
		case BOUND:
		default:
			return consequent + " must be bound";
		}
	}

	private static String antecedentPhrase(Alternative antecedent) {
		// Antecedent members are OR-combined ("any one triggers"), so they read with "or".
		return orList(antecedent.getBindingNames()) + " is bound";
	}

	/**
	 * A {@code <choose>} alternative list, {@code and}-joined: the alternatives together form the set
	 * the cardinality ranges over ("one of a, b and c"). An {@code <any-of>} alternative is shown as a
	 * parenthesized {@code or}-group.
	 */
	private static String alternativeList(List<Alternative> alts) {
		final List<String> parts = new java.util.ArrayList<>(alts.size());
		for (final Alternative alt : alts) {
			parts.add(alt.isAnyOf() ? "(" + orList(alt.getBindingNames()) + ")" : quote(alt.getBindingNames().get(0)));
		}
		return joinList(parts, "and");
	}

	/** {@code or}-joined quoted binding names ("a", "a or b", "a, b or c"). */
	private static String orList(List<String> names) {
		final List<String> parts = new java.util.ArrayList<>(names.size());
		for (final String n : names) {
			parts.add(quote(n));
		}
		return joinList(parts, "or");
	}

	/** Joins already-rendered parts as "a", "a {conj} b", or "a, b {conj} c" (no Oxford comma). */
	private static String joinList(List<String> parts, String conjunction) {
		final int n = parts.size();
		if (n == 0) {
			return "";
		}
		if (n == 1) {
			return parts.get(0);
		}
		final StringBuilder b = new StringBuilder();
		for (int i = 0; i < n; i++) {
			if (i > 0) {
				b.append(i == n - 1 ? " " + conjunction + " " : ", ");
			}
			b.append(parts.get(i));
		}
		return b.toString();
	}

	private static String quote(String s) {
		return "'" + (s == null ? "" : s) + "'";
	}
}
